### ISSUE TITLE
The list updates if I go into a profile and then back to the list.

### ISSUE THREAD

**Issue by FelixJohnsson** [rasmus-eklund/SaltTalentPool#23]
If I'm on https://talents.salt.dev/ and then go to a profile, and then go back. The list of candidates updates it's order. Is this a wanted behaviour?

**Comment by allanheremi** [comment]
@FelixJohnsson thank you for great feedback! 

It was initially wanted behaviour but upon further review, we concluded this is not optimal.
List will no longer update the search list upon returning, issue resolved.
